### ISSUE TITLE
Door lock not supported

### ISSUE THREAD

**Issue by jacha05** [PatchworkBoy/homebridge-edomoticz#77] opened 2017-02-19 16:35 UTC
Hi running with the newest version on domoticz. The door contact is changed to door lock witch means my doorlock is not supported by homebridge anymore. The device type is  now 19 instead av 11. 

{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "Locked",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "Zwave Plus USB",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000B01",
         "Image" : "Light",
         "InternalState" : "Locked",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-02-19 17:12:14",
         "Level" : 255,
         "LevelInt" : 255,
         "MaxDimLevel" : 100,
         "Name" : "Ytterdörr",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Locked",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Door Lock",
         "SwitchTypeVal" : 19,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "door",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "28"

**Comment by flic** [comment] 2017-04-22 13:06
I have the same problem. I tried changing DeviceTypeDoorLock in constants.js to 19 just to see what would happen, and that makes the door lock appear in HomeKit as a supported device. Lock/unlock works, but unfortunately the lock/unlock status is reversed.

**Comment by xTheRamon** [comment] 2017-05-01 08:22
Hi! Really really sorry for the late reply. I have just pushed a new commit (cc60d4d) where the door locks work as intended. The `door contact` type is also still in-tact.

I have also pushed this version to npm!

Closing...

**Closed by xTheRamon** 2017-05-01 08:22 UTC
