### ISSUE TITLE
EvoHome via Script (Heating system)

### ISSUE THREAD

**Issue by EdSt** [PatchworkBoy/homebridge-eDomoticz#13] opened 2016-02-13 16:16 UTC
Hi there,

Details for Honeywell EvoHome (using the script integration method), this is 1 heating zone information.

Many thanks

{
   "ActTime" : 1455379812,
   "ServerTime" : "2016-02-13 16:10:12",
   "Sunrise" : "07:25",
   "Sunset" : "17:18",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "23.0 C, (23.0 C), TemporaryOverride until 2016-02-13T23:30:00Z",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 20,
         "HardwareName" : "evohome",
         "HardwareType" : "Evohome via script",
         "HardwareTypeVal" : 40,
         "HaveTimeout" : false,
         "ID" : "621833",
         "LastUpdate" : "2016-02-13 16:10:08",
         "Name" : "Living Room",
         "Notifications" : "false",
         "PlanID" : "18",
         "PlanIDs" : [ 18 ],
         "Protected" : false,
         "SetPoint" : 23.0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "TemporaryOverride",
         "SubType" : "Zone",
         "Temp" : 23.0,
         "Timers" : "false",
         "Type" : "Heating",
         "TypeImg" : "override_mini",
         "Unit" : 9,
         "Until" : "2016-02-13T23:30:00Z",
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "363"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by PatchworkBoy** [comment] 2016-02-19 19:27
Could you get me all the different readings for...

`”Status"` : “TemporaryOverride”`

...please! (Either that or fire me a link to the script you’re using online and I should be able to get all I need from that... ta!)

**Comment by EdSt** [comment] 2016-02-19 19:37
Sure, it's the below:

https://www.domoticz.com/wiki/Evohome#Scripting_for_RFG100

The above scripts are executed by cron, then links in with this:

https://github.com/watchforstock/evohome-client

**Comment by PatchworkBoy** [comment] 2016-02-19 19:38
Ace - cheers...!

**Comment by PatchworkBoy** [comment] 2016-02-19 20:11
Am I correct in presuming the DHW device and Control device are fine being handled as plain switches (am assuming they already or you’d have requested them too?)

Reading & changing the setPoint itself should be doable within the native HomeKit thermostat type (always a bonus - means you get Siri control) - what’s the min & max it can be physically set to on the Honeywell (deg C)?

**Comment by EdSt** [comment] 2016-02-19 20:20
I have to be honest, I've not tried the hot water yet (DHW) with homebridge - although I'll give it a shot and report back.  It is just an on/off switch, but also shows/returns the current temperature (this can't be set, its part of the system setup on the unit itself i.e maximum temperature).

Zone temperatures can be set between 5 and 35 degree C.  With regards to setting an override, this is either a temporary (with a defined end time) or permanent - I guess it would either have to be hard coded, or a user defined type/period that applies to all?

Many thanks,

**Comment by PatchworkBoy** [comment] 2016-02-20 14:42
OK - VERY experimental support added in https://github.com/PatchworkBoy/homebridge-eDomoticz/commit/737339188e456022554601affa8242ca5426b956 - I’ve got no way to test this one at all!

This _should_ detect the device as a proper thermostat, whose and current and target states are always set to “Heat” (1).

You should get a slider representing current SetPoint, and a Target SetPoint slider which is your desired SetPoint temperature, and then an Override slider.

The Override slider is thus: 
0 = Mode Auto.
481 = Mode PermanentOverride with set point temperature.

Anything in between = value in minutes to add to current time, and use this as Temporary Override Until time. This gives you the ability to set the TempOverride until 8 hours in the future.

When reading back the TempOverride figure, that should give you the remaining time in minutes til the temp override time is reached.

Set the setPoint slide first, then the TempOverride slider.

Let me know how you get on...!

**Comment by EdSt** [comment] 2016-02-20 15:42
Phenomenal work, I shall have a play over the next day or so!  Many thanks,

**Comment by EdSt** [comment] 2016-02-20 15:50
Quick test, it errors when it reaches the zone - with the below - removing the zone from the roomplan and it starts correctly.

[eDomoticz] Initializing platform accessory 'Living Room'...
events.js:142
    throw TypeError('listener must be a function');
          ^
TypeError: listener must be a function
    at TypeError (native)
    at addListener (events.js:142:11)
    at Object.eDomoticzAccessory.getServices (/usr/lib/node_modules/homebridge-edomoticz/index.js:1217:99)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:237:36)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:223:32)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at callbackLater (/usr/lib/node_modules/homebridge-edomoticz/index.js:423:37)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-edomoticz/index.js:453:17)
    at Request.self.callback (/usr/lib/node_modules/homebridge-edomoticz/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)

**Comment by PatchworkBoy** [comment] 2016-02-20 16:14
Oops - update & try again (v0.1.15)

**Comment by EdSt** [comment] 2016-02-20 17:06
I only see 0.1.14?

**Comment by PatchworkBoy** [comment] 2016-02-20 17:08
Sorry - forgot the gitHub sync button... but had pushed it to npmjs. There now.

**Comment by EdSt** [comment] 2016-02-20 17:11
I only see 0.1.14 wth npm, sorry for not being clear

root@domoticz:~# npm -g list|grep edomoticz
├─┬ homebridge-edomoticz@0.1.14
root@domoticz:~# npm -g update
root@domoticz:~#

**Comment by PatchworkBoy** [comment] 2016-02-20 17:14
Just repushed to npm (so now 0.1.16) https://www.npmjs.com/package/homebridge-edomoticz

**Comment by EdSt** [comment] 2016-02-20 17:21
Weird, it wouldn't update, just explicitly specified the package name and installed then it seems to have taken it.  Same error unfortunately:

[eDomoticz] Initializing platform accessory 'Living Room'...
events.js:142
    throw TypeError('listener must be a function');
          ^
TypeError: listener must be a function
    at TypeError (native)
    at addListener (events.js:142:11)
    at Object.eDomoticzAccessory.getServices (/usr/lib/node_modules/homebridge-edomoticz/index.js:1217:99)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:237:36)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:223:32)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at callbackLater (/usr/lib/node_modules/homebridge-edomoticz/index.js:423:37)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-edomoticz/index.js:453:17)
    at Request.self.callback (/usr/lib/node_modules/homebridge-edomoticz/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
root@domoticz:~# npm list|grep domoticz
└─┬ homebridge-edomoticz@0.1.16

**Comment by PatchworkBoy** [comment] 2016-02-20 18:30
Give it another update and try again... (0.1.18)

**Comment by EdSt** [comment] 2016-02-20 18:48
Nicely done!  It starts, detects everything correctly and replies to 'what is the temperature in the living room?'

WIll have a play and report back, many thanks for your efforts!

**Comment by PatchworkBoy** [comment] 2016-02-20 18:50
If anything trips it up it’ll be changing the override slider ;)

**Comment by PatchworkBoy** [comment] 2016-02-21 16:49
Made some changes which will affect this - upgrade to 0.1.21...

**Comment by PatchworkBoy** [comment] 2016-03-04 20:03
> "Set it up today and am totally impressed with it! Just a small issue I run into. I have my evohome system connected to domoticz. Setting the temperature through siri/Eve works but as soon as I touch the override timer button homekit crashes (see below loging-info). Also don't understand how the general "evotouch" device is working. It seems I can change it's temp in e.g Eve but that command is not recognized. Changing the Mode (currently Heating) to anything else (off/heat/cool/auto) does not seem to trigger anything.”

```
[Domoticz] Setting thermostat SetPoint to 21
[Domoticz] Achterkamer sent command successfully
Loaded plugin: homebridge-edomoticz
Registering accessory 'homebridge-edomoticz.eDomoticz’
Registering platform 'homebridge-edomoticz.eDomoticz’
---
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
[Domoticz] Initializing eDomoticz platform...
[Domoticz] Fetching Domoticz lights and switches...
Loading 0 accessories...
[Domoticz] Initializing platform accessory 'Achterkamer’...
[Domoticz] Initializing platform accessory 'Alexander’...
[Domoticz] Initializing platform accessory 'Circle afzuiger switch’...
[Domoticz] Initializing platform accessory 'Eettafel’...
[Domoticz] Initializing platform accessory 'EvoTouch Colour’...
[Domoticz] Initializing platform accessory 'Hue Gang’...
[Domoticz] Initializing platform accessory 'P1 Electricity’...
[Domoticz] Initializing platform accessory 'Voorkamer’...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

[Domoticz] Static Data for EvoTouch Colour: 1
[Domoticz] Setting thermostat SetPoint to 10
[Domoticz] There was a problem sending command toEvoTouch Colour
[Domoticz] undefined
[Domoticz] Setting thermostat SetPoint to 10.5556
[Domoticz] There was a problem sending command toEvoTouch Colour
[Domoticz] undefined
```

[Bink @ Domoticz Forums](https://www.domoticz.com/forum/viewtopic.php?f=36&t=10272&p=77805#p77805)

**Comment by DJBenson** [comment] 2016-03-12 00:11
I've just set up Domoticz and linked it to homebridge and everything is pretty much rock solid, with the exception of one issue with the homebridge-edomoticz plugin; I think it's similar to the one above about setting a temporary setpoint temperature. If I use the Domoticz web UI, the temp setpoint works perfectly and is represented on the Evohome controller with it's end time. If however I use one of may HomeKit apps (currently using "eve") to set the time using the exposed slider, homebridge crashes with the following error;

```
Fri, 11 Mar 2016 23:58:20 GMT Accessory [myBridge] Processing characteristic set: [{"aid":20,"iid":14,"value":75}]
Fri, 11 Mar 2016 23:58:20 GMT Accessory [myBridge] Setting Characteristic "Override (Mins, 0 = Auto, 481 = Permanent)" to value 75
/usr/local/lib/node_modules/homebridge-edomoticz/index.js:886
                      that.log("Setting thermostat SetPoint to " + setpoint +", mode to " + mode);
                                                                   ^
ReferenceError: setpoint is not defined
    at /usr/local/lib/node_modules/homebridge-edomoticz/index.js:886:68
    at Array.map (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-edomoticz/index.js:878:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-edomoticz/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-edomoticz/node_modules/request/request.js:1082:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-edomoticz/node_modules/request/request.js:1009:12)
```

Any idea's?

**Comment by PatchworkBoy** [comment] 2016-03-12 18:01
Update via npm and give it another whirl n’ let me know...!

**Comment by DJBenson** [comment] 2016-03-12 22:55
Hi - the override slider is no longer causing Homebridge to crash but I still don't think it's behaving as intended unless I've got it wrong;

In the app (again I'm using "eve") I set my target temperature then set the slider for the number of minutes I want the override to apply for - if this is the correct process so far then the outcome is incorrect...the thermostat is reporting any changes using the above method as "PermanentOverride" instead of "Override until...". Using the official Honeywell app confirms the same (icon indicating permanent override). The only way to clear the override is via the Domoticz page or using the Honeywell app.

I'm very new to HomeKit but I believe the "eve" app is simply interacting with the controls made available via the Homebridge application (and of course your plugin) so I think this is a quirk of the plugin rather than the app - of course you know a lot more than I do so happy to be challenged :)

**Comment by PatchworkBoy** [comment] 2016-03-13 09:48
Am adding this support 'blind' - I don't have an EvoHome to test with - so all feedback helps...! Still working on it bit-by-bit!

**Comment by DJBenson** [comment] 2016-03-13 10:13
Yeah totally understand. I'll help out however I can, if you need me to test something I'm up for it. I'm fairly proficient in most areas of IT just not a massive coder or I'd have a crack myself :-)

**Comment by DJBenson** [comment] 2016-03-13 10:25
I have an idea for how I can help you if you want to take me up on the offer. We have one zone in our system which is not really used. What I could do if you like is set you up as an additional user then you'll get your own login to the evohome platform against which you can test in this spare zone.

Let me know if that's of interest to you.

**Comment by PatchworkBoy** [comment] 2016-04-02 14:11
Should hopefully be fixed now via https://github.com/PatchworkBoy/homebridge-eDomoticz/commit/987f18a43394e3ee10cad9a58cd582a1a92901c0

**Comment by PatchworkBoy** [comment] 2016-04-08 09:36
Closing as 'presumed fixed'. If someone notifies me otherwise, I'll reopen.

**Closed by PatchworkBoy** 2016-04-08 09:36 UTC
Labels: enhancement
