### ISSUE TITLE
Expose Fibaro FGMS-001 motion sensor as a sensor and not as a switch

### ISSUE THREAD

**Issue by ooii** [PatchworkBoy/homebridge-edomoticz#78] opened 2017-03-21 15:58 UTC
Hi,

I have a Fibaro FGMS-001 that I use through domoticz and I'm using homebridge-edomoticz to expose my domoticz to HomeKit.
I have also a hue system configured in HomeKit and I wanted to switch on the hue lights automatically when a motion is detected by this Fibaro sensor. But, the problem is that the motion sensor is exposed in domoticz as a switch and not as a sensor, which causes a problem for automation. The automation is executed only if my iPhone is running the Home app, which is not the case of my Hue sensors (which are exposed as sensors). Note that I have an Apple TV running as a HomeKit hub.
Any idea how I can fix/change that?
Thank you very much for your help.

**Comment by ooii** [comment] 2017-03-30 20:39
Hi, 

Ding.

**Comment by xTheRamon** [comment] 2017-04-13 15:06
Hello,

Sorry for the late reply. I don't really have a solution for you at the moment if you're using automation. The problem is that the sensor is seen as a 'switch' in Domoticz. I think if the sensor is added to the 'motion sensors' list in Domoticz, it would function a lot better, since iOS knows it is a motion sensor. I'm not sure if automation would also see the change without having the app open.

I would suggest you use Domoticz events or maybe node-red for automation. You're very limited in iOS' automation in my opinion. It is easily doable in Domoticz events though.

**Comment by ooii** [comment] 2017-04-14 21:57
Thanks for the reply. I was expecting something like that :)

**Comment by xTheRamon** [comment] 2017-04-15 05:46
Allright! If you need any help using Domoticz events don't hesitate to ask. Closing this for now...

**Closed by xTheRamon** 2017-04-15 05:46 UTC
