### ISSUE TITLE
Scenes support

### ISSUE THREAD

**Issue by poudenes** [PatchworkBoy/homebridge-edomoticz#84] opened 2017-06-03 06:38 UTC
Hi there,

didn't know where to ask this. Does eDomoticz will support scenes from Domoticz into Homebridge?
Reason i ask is because i have a Nanoleaf Aurora lights and from their app they push scenes into Homekit. So wondering if this also can be done by eDomoticz :)

**Comment by xTheRamon** [comment] 2017-06-06 08:01
Hiya!

Scenes are not supported. (yet!)

I'll have to figure out if I can get scenes working and if there is homebridge support for scenes.
I'll have a look at the Nanoleaf app too!

**Comment by poudenes** [comment] 2017-06-07 09:09
Hi There,

Lets hope you will find a way to let it work :D
to bad im not a programmer… grrr

Cheers,

**Comment by xTheRamon** [comment] 2017-06-08 14:00
Heya,

I have checked again and stumbled upon an old post of 'Marci', the author of this plugin.

```
q: Are Domoticz SCENES supported? 
a: Not directly, but there's a straightforward workaround. Create a dummy/virtual/manual switch in Domoticz and set the On action to trigger the scene (see https://www.domoticz.com/wiki/Domoticz_ ... _on_or_off ), and an Off delay to reset the switch. 
eDomoticz / Homebridge will see the virtual switch.
```

The problem is that Domoticz exposes their scenes using an API, so we can get all scenes from Domoticz. There is, however, no way to make Homekit aware of the scenes. There is simply no API in homebridge to send the scenes over to homebridge / your homekit app.

**Comment by poudenes** [comment] 2017-06-09 12:08
Hi there,

And there is no way to made some updates to homebridge so it can push scenes from domoticz into homekit?
The nano leaf app can push, also philips hue app can. So its not a option that can’t be done.

To bad im not a programmer … 

Cheers,
Peter

**Comment by xTheRamon** [comment] 2017-06-09 13:01
Hi Peter,

Well, you can add scenes in Homekit but they will show up as a switch. That is the workaround I posted above.
There is no possibility for now to push real scenes to homekit using homebridge. (Below screenshot)
Let's hope there will be support for this in the future.

![Scenes](https://homekitcompatible.com/wp-content/uploads/2016/06/homekit-scene-good-night-1024x697.jpg)

**Comment by poudenes** [comment] 2017-06-09 15:42
Yes im also using switches to make a workaround… :) its working… but we all want it the way how it has to be… hahaha :)

**Comment by xTheRamon** [comment] 2017-07-20 12:46
Haha I'll keep this top of mind whenever Apple add support for custom scenes. Closing...

**Closed by xTheRamon** 2017-07-20 12:46 UTC
Labels: enhancement
