### ISSUE TITLE
Netatmo CO2 not working

### ISSUE THREAD

**Issue by mayer-gbr** [PatchworkBoy/homebridge-edomoticz#69] opened 2016-12-27 09:21 UTC
The last update produces a crash of the homebridge server when reading CO2 values from domoticz. If those netatmo sensors are deactivated, homebridge starts: (Debian 8). Before the update of the node modules, everything worked. 
------------------
/usr/local/lib/node_modules/homebridge-edomoticz/lib/domoticz_accessory.js:1194
                                        airQualityService.getCharacteristic(Characteristic.AirParticulateDensity).on('get', this.getValue.bind(this));
                                                                                                                 ^
TypeError: Cannot read property 'on' of undefined
    at Object.eDomoticzAccessory.getServices (/usr/local/lib/node_modules/homebridge-edomoticz/lib/domoticz_accessory.js:1194:79)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:364:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-edomoticz/index.js:197:7)
    at Request._callback (/usr/local/lib/node_modules/homebridge-edomoticz/lib/domoticz.js:78:9)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-edomoticz/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-edomoticz/node_modules/request/request.js:1082:10)

**Comment by xTheRamon** [comment] 2017-01-03 15:52
Excuse me for the late reply.

I have just resolved this issue in the latest commit.

Can you please update to the latest version (git or through npm) and let me know if the issue is resolved?

Thank you!

**Comment by AbsolutK** [comment] 2017-01-05 14:07
Hi xTheRamon,

I can report the issue is solved now. Running the latest builds (through npm) of both homebridge and eDomoticz. Thanks a lot!

**Comment by xTheRamon** [comment] 2017-01-05 14:15
Coolio! Closing...

**Closed by xTheRamon** 2017-01-05 14:15 UTC
Labels: response wanted
