### ISSUE TITLE
New Domoticz blinds support bug introduced in 2.1.40, always using legacy commands

### ISSUE THREAD

**Issue by ThomasRobertFr** [PatchworkBoy/homebridge-edomoticz#253] opened 2022-12-20 20:54 UTC
Hello,

I have an up-to-date setup with Domoticz and Homebridge + edomoticz plugin. In domoticz, I have some "EU venitican blinds" devices set up.

When I click on the open/close buttons from Domoticz UI, it's behaving as expected. However, from Homebridge, it's reversed: the "open" action makes them close and the other way around.

I think the problem might come from the fast that my blinds are of type "RFY", and the [code in the latest PR](https://github.com/PatchworkBoy/homebridge-edomoticz/pull/251/commits/993870f82c8132ce7ff2256b86820749d346fd03#diff-7c708c987fbb821cb762b6d377c3cbb04be6cad843f0d5dbd49b81f0244f0c67R1296) does `if (message.stype == 'RFY') { position = 100 - position; }`. Indeed, in domoticz I had to check "Reverse Open/Close state" so that Domoticz UI open button indeed opens my blinds. This might be related.

Thanks a lot for this work and I'm completely available to help fixing this.

**Comment by ThomasRobertFr** [comment] 2022-12-20 20:55
@ksacca since you worked on the PR, maybe it makes sense to mention you in this issue?

**Comment by ksacca** [comment] 2022-12-20 21:58
Sorry for the issue. As I said on the domoticz forum, I don’t own any Venetian blinds and have no idea how they work. 
That’s why I waited more than a month before making a PR with my changes (hoping some bugs might get detected). I’ll have a look at it tomorrow and might ask you to test a few things.

**Comment by ThomasRobertFr** [comment] 2022-12-21 10:01
Hi! first, thanks for your prompt reply @ksacca and please don't apologise ;) I investigated further the issue on my side. First, I am using MQTT with Domoticz.

When I look at the messages sent there, here is what I get :

```
# Open command from Homebridge / Google Home
{"command":"switchlight","idx":29,"switchcmd":"Off"}
# Close command from Homebridge / Google Home
{"command":"switchlight","idx":29,"switchcmd":"On"} 
```

If I disable MQTT, I see the same On/Off commands received by the API in the logs.

On the other hand, Domoticz UI directly call Domoticz API and here are the calls being made:

```
# Open command from Domoticz UI
http://192.168.1.10:8080/json.htm?type=command&param=switchlight&idx=29&switchcmd=Open&level=0&passcode=
# Close command from Domoticz UI
http://192.168.1.10:8080/json.htm?type=command&param=switchlight&idx=29&switchcmd=Close&level=0&passcode=
```

For me, it seems that the commands should be Open/Close after your PR so I'm now quite unsure about the real source of the bug 🤔 

Of course my version is 2.1.40 and the legacy blinds config option is set to 0. I'll keep looking

**Comment by ksacca** [comment] 2022-12-21 10:32
@ThomasRobertFr I'm a coding enthousiast and like to learn, but I am not a developer. It was my first PR, so that's maybe why I feel the need to appologise 🤣.

The issue is not in the code `if (message.stype == 'RFY') { position = 100 - position; }` since this is only used if legacy blinds is set to 1 (for the old way). Nothing changed there.

In your case, the subtype might be RFY, but as you have venetian blinds, the previous check will evaluate to true (`else if ((this.swTypeVal == Constants.DeviceTypeBlindsVenetianUS || this.swTypeVal == Constants.DeviceTypeBlindsVenetianEU) && message.nvalue > 1)`) so the RFY type will never be checked. But thanks to your remark I also found an issue for Regular RFY blinds which I tried to fix. These blinds use an nvalue 1 for open and 3 for close (and vice versa if reversed state is on). Normal blinds use nvalue 1 and 0.

I suppose you use Venetian blinds of type US and not EU. US venetian blinds uses nvalue of 15 and 16. As you can see in the code, only nvalue == 15 was evaluated. But EU venetian blinds uses nvalues 17 and 18 so I suppose they never worked with this plugin.


Could you replace the code starting from line 1317 utnil 1327 with this code. I was able to create dummy RFY blinds (including venetian EU and US) and all possible reversed combinations worked for me:

```
                        } else if ((this.swTypeVal == Constants.DeviceTypeBlindsVenetianUS || this.swTypeVal == Constants.DeviceTypeBlindsVenetianEU) && message.nvalue > 1) {
                            //position = (message.nvalue == 15 ? 100 : 0);
                            if (message.ReverseState == 'true') {
                                position = ((message.nvalue == 16 || message.nvalue == 18)  ? 100 : 0);
                            } else {
                                position = ((message.nvalue == 15 || message.nvalue == 17) ? 100 : 0);
                            }
                        } else {
                            if (message.ReverseState == 'true') {
                                position = (message.nvalue == 1 ? 0 : 100);
                            } else {
                                position = (message.nvalue == 1 ? 100 : 0);
                            }
                          }
                    }
```

**Comment by PatchworkBoy** [comment] 2022-12-21 11:39
@ThomasRobertFr unintentional - mistake my end at a guess whilst merging several revisions... drop in a PR to undo it and I'll merge it straight in and push up 2.1.41

**Comment by ksacca** [comment] 2022-12-21 11:48
@ThomasRobertFr Could you test my changes on your RFY blinds first (if possible also by changing your Venetians temporary to regular RFY blinds)? If this works for you as well, you can include it in your PR. Thank you already for testing.

**Comment by PatchworkBoy** [comment] 2022-12-21 11:50
Hold up a mo...! Just grab domoticz_accessory.js from GitRepo and drop it over your current copy and restart homebridge and see if that resolves. This chunk of code was missing from the merges after a few minor fixes at my end to another device type:

` if (this.platform.config.legacyBlinds == 1) {
            var command = (shouldOpen ? "On" : "Off");
        } else {
            var command = (shouldOpen ? "Close" : "Open");
        }`

**Comment by PatchworkBoy** [comment] 2022-12-21 12:04
*Nudge to notify of edit to above post*

**Comment by ksacca** [comment] 2022-12-21 13:40
I tested:

- regular blinds, blinds + stop, blinds percentage (real hardware, both zigbee and zwave)
- venetian EU & US (but dummy devices)
- venetian EU & US RFY (but dummy devices)
- RFY regular blinds (not percentage as this is not supported, dummy too).

All of the above was tested with the option Reverse enabled and disabled. I didn't detect any issues during testing, but it would be nice if @ThomasRobertFr could test it as he owns the real hardware. So for me it is OK now.

Thank you again @PatchworkBoy for your work on this project. Next to domoticz itself, this is the most used feature in our home. Couldn't live without it (mainly for the WAF 🤣 ).

If possible, could you also add the info about dimfix and legacyblinds to the readme? I believe it was also removed from my PR by accident, see https://github.com/PatchworkBoy/homebridge-edomoticz/commit/9e08e09e93204da05aa8c2df7ba30eaf1be13982.

**Comment by PatchworkBoy** [comment] 2022-12-21 21:08
Done - now at 2.1.44... with minor tweak to resolve https://github.com/PatchworkBoy/homebridge-edomoticz/issues/200

**Comment by ksacca** [comment] 2022-12-21 21:18
Thanks. I posted a message on the domoticz forum to inform the users.

**Comment by watchaaa** [comment] 2022-12-23 03:12
Hi,
I switched back to the previous version 2.1.39 because blinds are working inverted with the 2.1.40.
2.1.39 is working perfectly with new domoticz blinds system, but 2.1.40 made problems (some blinds inverted), even if I change "blinds system legacy" in advanced settings.

**Comment by ksacca** [comment] 2022-12-23 07:56
In version 2.1.40 there was an issue where a crucial part of the PR for the new blind system was overwritten by other changes. This has been fixed in version 2.1.41. We should now be at 2.1.45 which fixes some bugs for venetian and RFY blinds, but I see npm is still at version 2.1.40. You can see when the version is updated if you go to https://www.npmjs.com/package/homebridge-edomoticz.

**Comment by ThomasRobertFr** [comment] 2022-12-23 09:02
@PatchworkBoy Can you publish the latest versions on npm so that I can test the fixes properly?

Again, thanks a lot for your quick reaction on this!

**Comment by PatchworkBoy** [comment] 2022-12-23 09:54
Done...

**Comment by watchaaa** [comment] 2022-12-23 10:07
Hi,
now the 2.1.45 version is in homebridge (but the release notes in pop up are still for 2.1.41)
I confirm that now everything is working good with the 2.1.45 version !
Thanks for the great work !

**Closed** 2022-12-23 11:27 UTC
